lsi: false
safe: true
source: darrinseats
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
domain: darrinseats.github.io
url: https://darrinseats.github.io
  #baseurl: /darrinseats/
remote_theme: b2a3e8/jekyll-theme-console
plugins:
- jekyll-remote-theme
title: Project page of Darrin Seats
