lsi: false
safe: true
source: darrinseats
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
domain: darrinseats.github.io
url: https://darrinseats.github.io
baseurl: /darrinseats/
