lsi: false
safe: true
source: darrinseats
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
domain: darrinseats.github.io
url: https://darrinseats.github.io
  #baseurl: /darrinseats/
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
